### ISSUE TITLE
This doesn't work: go install github.com/fiatjaf/nak@latest

### ISSUE THREAD

**Issue by basantagoswami** [fiatjaf/nak#15]
Running it gives me:

`go: github.com/fiatjaf/nak@latest (in github.com/fiatjaf/nak@v0.1.13): go.mod:5: unknown directive: toolchain`

I'm on Ubuntu, installed go using:

`sudo apt install golang-go`

Also, `go version` gives me:

`go version go1.18.1 linux/amd64`

**Comment by fiatjaf** [comment]
That Go version is 2 years old. Ubuntu is such a pain, no one should use it.

If you're not planning on writing Go I recommend that you use the binary.

Otherwise I recommend https://go.dev/dl/
