### ISSUE TITLE
nak doesn't support nip05

### ISSUE THREAD

**Issue by patrickReiis** [fiatjaf/nak#19]
It'd be good if nak supported nip05, so people could do:
```
nak req -k 0 -a patrick@patrickdosreis.com gleasonator.dev/relay | jq
```
instead of 
```
nak req -k 0 -a 47259076c85f9240e852420d7213c95e95102f1de929fb60f33a2c32570c98c4 gleasonator.dev/relay | jq
```

**Comment by fiatjaf** [comment]
`nak req -k 0 -a $(nak decode patrick@patrickdosreis.com | jq -r .pubkey) gleasonator.dev/relay | jq` should work now.

**Comment by fiatjaf** [comment]
`nak fetch patrick@patrickdosreis.com` should also work now.

**Comment by patrickReiis** [comment]
I am sleeping in the chairs of an international Airport, will test once I come back home, but it is likely it's working...

**Comment by patrickReiis** [comment]
All working, that's some seamless experience right there.
