### ISSUE TITLE
nak quits too quickly to show events when not using --stream with --auth

### ISSUE THREAD

**Issue by jeremyd** [fiatjaf/nak#20]
Noticed this today, when querying a relay with AUTH enabled, nak runs so quickly it just says "ok" and no events.  However, when using --stream, it shows the events.

**Comment by fiatjaf** [comment]
Can you give me a reproducible example?
When not using `--stream` `nak` should quit after getting an `EOSE`.

**Comment by jeremyd** [comment]
Ah, ok, this makes sense.  I realized my relay implementation is broken, it sends EOSE during the auth flow when it sends the CLOSE, auth-required.  I coulda sworn this was in the spec, but I re-read it today and it's not (anymore?).  Anyway, will fix on the relay side and close this.
