### ISSUE TITLE
`since` changes on reconnection

### ISSUE THREAD

**Issue by nanikamado** [fiatjaf/nak#24]
When a relay connection is temporally lost and reconnected, `since` seems to be overwritten with the time at that point even if it is specified by the command line argument. 

```
$ bash -c 'timeout 1 websocat -s 8077 ; timeout 5 websocat -s 8077' & timeout 6 nak req --since 1 --stream ws://localhost:8077 & wait
Listening on ws://127.0.0.1:8077/
connecting to ws://localhost:8077... ok.
["REQ",":1",{"since":1,"limit":0}]
Listening on ws://127.0.0.1:8077/
["REQ",":2",{"since":1721403791,"limit":0}]
```

**Comment by fiatjaf** [comment]
That is by design, see here: https://github.com/nbd-wtf/go-nostr/blob/81a396be565e2dc34cf1370bbf8d81c3634556d2/pool.go#L190-L199

**Comment by nanikamado** [comment]
I see. Thanks.
