### ISSUE TITLE
Cannot update nak to latest

### ISSUE THREAD

**Issue by mplorentz** [fiatjaf/nak#26]
I tried to update nak by running `go install github.com/fiatjaf/nak@latest` but it says:
```
go: github.com/fiatjaf/nak@latest (in github.com/fiatjaf/nak@v0.4.2):                                     
        The go.mod file for the module providing named packages contains one or                           
        more replace directives. It must not contain directives that would cause                          
        it to be interpreted differently than if it were the main module.
```

The AI told me to contact the maintainer, and I do whatever AI tells me to.

`go version go1.22.5 darwin/arm64`

**Comment by fiatjaf** [comment]
Oh, wow. Thank you for opening this, I didn't know `go install` behaved like that.

My `replace` directive is purely deterministic, so it shouldn't be triggering this error, but apparently https://github.com/golang/go/issues/44840 disagrees and sees no reason to fix this bug.

I guess I'll have to do something.

**Comment by fiatjaf** [comment]
Should work now on v0.5.0.
