### ISSUE TITLE
nak doesn't set empty content

### ISSUE THREAD

**Issue by patrickReiis** [fiatjaf/nak#32]
@Alexgleason removed my mighty pin list.

Now I'm trying to create a new kind 10001 event, and it's all good except for the content field, which uses the default value (hello from the nostr army knife).  

I tried first this:
```
nak event -c '' -e 757f2cad8e4a6e74d7bafc2ec02cbcb5596d3fda4a081cc72a54d4874555c1ad --sec <my-sec> | jq
```
And then this: 
```bash
echo '{"content": ""}' | nak event -e 757f2cad8e4a6e74d7bafc2ec02cbcb5596d3fda4a081cc72a54d4874555c1ad --sec <my-sec> | jq
```  

For me personally I would let the content as it is, like a meme, but the NIP says the content must be a private/encrypted event, so in order not to break stuff I prefer to let it empty.

I think the solution would be to create a boolean flag that sets the content to empty?

**Comment by fiatjaf** [comment]
The default content is only set when you specify `--kind 1` (or when you don't specify the kind, as it defaults to 1). If you have used `-k 10001` there it would have worked.

But this is also a bug since empty content on kind 1 should be possible.

**Comment by patrickReiis** [comment]
Indeed, thanks.  
Doing the wrong thing (forgetting the kind flag) led me to finding a right thing (bug) accidentally.
