### ISSUE TITLE
nak doesn't support AND filter

### ISSUE THREAD

**Issue by patrickReiis** [fiatjaf/nak#33]
Say I want to stalk someone. I would do something like this:

```bash
nak req -k 1 -t p=3bf0c63fcb93463407af97a5e5ee64fa883d107ef9e558472c4eb9aaaefa459d -a 0461fcbecc4c3374439932d6b8f11269ccdb7cc973ad7a50ae362db135a474dd gleasonator.dev/relay | jq
```  

Which means, I'd have pubkey A and pubkey B, and I want to see all kind 1s that contain both pubkeys as tags.

Currently, nak only shows kind 1s that have at least pubkey A or B in the tags, but I want it to show only kind 1s that contain both pubkey A and B.

**Comment by fiatjaf** [comment]
That's not supported by relays and it probably shouldn't.

**Comment by patrickReiis** [comment]
Why shouldn't?
