### ISSUE TITLE
Does nak supports any tag keys?

### ISSUE THREAD

**Issue by patrickReiis** [fiatjaf/nak#39]
Maybe I'm doing this wrong, I'd like to get all kinds 1s of me, where the zap tag contains a value which is my pubkey, like so:

```
nak req -k 1 -a 47259076c85f9240e852420d7213c95e95102f1de929fb60f33a2c32570c98c4 -t zap=47259076c85f9240e852420d7213c95e95102f1de929fb60f33a2c32570c98c4 gleasonator.dev/relay | jq
```

Output:
```
parse error: Invalid numeric literal at line 1, column 8
```

It's almost midnight where I live, maybe I'm not thinking this straight. Also, the zap tag may contain more arguments, like weight and message, supposing nak does support querying by zap tag key and zap tag value, do I also need to fulfill the other values?

Like so:
```
nak req -k 1 -a 47259076c85f9240e852420d7213c95e95102f1de929fb60f33a2c32570c98c4 -t zap=[47259076c85f9240e852420d7213c95e95102f1de929fb60f33a2c32570c98c4, 2] gleasonator.dev/relay | jq
```

**Comment by fiatjaf** [comment]
That's not how Nostr filters work. Read NIP-01. You might be interested in the `"p"` tag instead. You can also try `nak` without specifying a relay in order to see the generated filters.
