### ISSUE TITLE
why when event kind==0, then event kind=1

### ISSUE THREAD

**Issue by shaibearary** [fiatjaf/nak#6]
https://github.com/fiatjaf/nak/blob/795e98bc2e7a1ddd26b04d7cc6f0c10bf472b122/event.go#L140-L146

**Comment by fiatjaf** [comment]
Because Golang is stupid. I'll fix it with a crazy hack. Why did you close the issue?

**Comment by fiatjaf** [comment]
Should be fixed now.

**Comment by shaibearary** [comment]
> Because Golang is stupid. I'll fix it with a crazy hack. Why did you close the issue?

because i thought its your another genius design which out of my understanding-zone :)

**Comment by fiatjaf** [comment]
> because i thought its your another genius design which out of my understanding-zone :)

You should never assume that!
